# Generated by Django 3.1.7 on 2021-03-31 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_creare', models.DateField(auto_now_add=True, null=True)),
                ('nume', models.CharField(max_length=255, null=True)),
                ('url', models.URLField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pret',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valoare', models.FloatField()),
                ('data_creare', models.DateField(auto_now_add=True, null=True)),
                ('produs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.produs')),
            ],
        ),
    ]
