# Generated by Django 3.1.7 on 2021-05-07 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20210506_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='lista',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
